### ISSUE TITLE
参照Readme安装 没办法运作

### ISSUE THREAD

**Issue by orsmile** [JixunMoe/proxy-163#4]
如题...

想说试看看这个TOOL 但我这边没办法正常使用(在台湾)

**Comment by jixunmoe** [comment]
具体什么状况呢？比如出错时的错误信息

可能忘了写了，试试 `reload-cache.cmd` ?

**Comment by orsmile** [comment]
[CUWCL4C][INFO] Request from server:  [21794834]
m2.music.126.net/zaRUP2TklcdnxhuEBES8kA==/2111062325349615.mp3:1 GET http://m2.music.126.net/zaRUP2TklcdnxhuEBES8kA==/2111062325349615.mp3 net::ERR_CONNECTION_TIMED_OUT
m2.music.126.net/TR3fR-zIg9BRQbGli651NA==/1888960976547614.mp3:1 GET http://m2.music.126.net/TR3fR-zIg9BRQbGli651NA==/1888960976547614.mp3 net::ERR_CONNECTION_TIMED_OUT

错误信息如上

但如果按下载是可以听的 只是播放器不能运作 看来拨放器的网址没转址?
http://127.0.0.1:4003/m2.music.126.net/HwswY97KVyYIyrmK5BiLkQ==/1888960976547612.mp3
是可以抓的

**Comment by jixunmoe** [comment]
啊对我没转址.. 等下修复..

因为我最开始是直接用代理工具代理了 `m*.music.126.net` 转发 HTTP 流量到这个地址，然后想到用 Aria2 下载就实现了 `http://127.0.0.1:4003/` 前缀下载。

很快，等我，真的非常抱歉 ><

**Comment by jixunmoe** [comment]
應該修正好了，請更新最新版本測試 :D

**Comment by orsmile** [comment]
已测试成功!
